# ANOVA 분석 복습- 220111

In [ ]:
import scipy.stats as spt
import numpy as np
import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm

분석을 하기 전에 먼저 하는 일들이라고 하였다. 

샤피로 테스트로는 정규분포를 따르는지 않는지 확인한다.
레빈테스트, 바틀렛: 등분산성 테스트
qq plot, redgedual 

테스트를 동시에 다 한 다음, 

사후검정을 했는데, 비교를 할 때, 짝지어 비교하는 집단에 대해서, 모든 방법으로 진행을 한 다음, 결과를 보고서 해석 할 때 내가 취사선택 해서 가져오면 안된다. 가장 나은것 한가지를 가져와서 쓰던지.


In [ ]:
# 정성적인 부분들 빼고 정량적인 것만 했다.

data2=pd.read_csv('temp.csv')

print(spt.shapiro(data2.SCORE[data2.GRADE=='fre']),'\n')
print(spt.shapiro(data2.SCORE[data2.GRADE=='sop']),'\n')
print(spt.shapiro(data2.SCORE[data2.GRADE=='jun']),'\n')
print(spt.shapiro(data2.SCORE[data2.GRADE=='sen']),'\n')

print(spt.levene(data2.SCORE[data2.GRADE=='fre'],data2.SCORE[data2.GRADE=='sop'],
                 data2.SCORE[data2.GRADE=='jun'],data2.SCORE[data2.GRADE=='sen']),'\n')

print(spt.bartlett(data2.SCORE[data2.GRADE=='fre'],data2.SCORE[data2.GRADE=='sop'],
                   data2.SCORE[data2.GRADE=='jun'],data2.SCORE[data2.GRADE=='sen']))

ShapiroResult(statistic=0.9097163081169128, pvalue=0.2115684449672699) 

ShapiroResult(statistic=0.9328135251998901, pvalue=0.41089069843292236) 

ShapiroResult(statistic=0.9695447683334351, pvalue=0.9059768915176392) 

ShapiroResult(statistic=0.9313449859619141, pvalue=0.39458659291267395) 

LeveneResult(statistic=0.29485921693349876, pvalue=0.8288903318657788) 

BartlettResult(statistic=0.7750467373461302, pvalue=0.8554257361613797)


정규분포도, 등분산성도 만족하는 것으로 나왔다. 0.05 근처에만 안나오면 됩니다!
(둘 다 고려를 해서 둘 다 결과가 거의 비슷하게 나오지만, 보통은 레빈을 더 많이 쓴다고 하신다. 그러나 통계이기 때문에 여러 방법을 통해서 뒷받침을 해주는 것이 좋다.)


독립성은 카이제곱등을 쓸 수 있지만, 독립성은 랜덤샘플링을 했을 때면 다 만족한다고 가정한다.

정규성이나 등분산성은 모집단을 모르기에, 랜덤샘플링을 하더라도 만족하지 않을 수 있다. 그러나 적어도 랜덤으로 뽑게되면 독립성은 만족한다(수학적으로 증명 가능)

샤피로도 좋지만, qq plot도 쓰고 여러가지를 해본다.

분석을 할 때에는 여러 방법으로 다 검정을 해보는 것이 좋다. 만족 하는 것을 많이 붙일 수록 신뢰도를 더 높일 수 있는 것과 같은 듯.

샘플링을 다시해야하는 것은 아노바를 못쓴다는 것과 같다.

In [ ]:
# 종속변수(점수) 독립변수(학년). 요인이 한가지인 간단한 예제.

print(spt.f_oneway(data2.SCORE[data2.GRADE=='fre'],data2.SCORE[data2.GRADE=='sop'],
             data2.SCORE[data2.GRADE=='jun'],data2.SCORE[data2.GRADE=='sen']),'\n') # 싸이파이는 결과만 보여주고, 

model2=ols('SCORE ~ C(GRADE)',data=data2).fit() #얘는 테이블로 보여준다.
anova_lm(model2)

F_onewayResult(statistic=0.7496788922095763, pvalue=0.5284052378268367) 



df        sum_sq     mean_sq         F    PR(>F)
C(GRADE)   3.0   1241.395833  413.798611  0.749679  0.528405
Residual  44.0  24286.583333  551.967803       NaN       NaN

평균을 낸 것은 수치가 의미가 있기 때문에 낸 것이다. 적어도 분산, 회귀, 등 종속변수는 수치형으로 나타낼 수 있어야 한다. 

그게 그렇지 않다면 중앙값등으로 나타낼 수 있어야 함.

분산분석은 명목형 자료라는 것이 차이가 있다.

(선형회귀분석은 수치형 자료)

In [ ]:
print(spt.shapiro(data2.SCORE[data2.CLASS=='A']),'\n')
print(spt.shapiro(data2.SCORE[data2.CLASS=='B']),'\n')
print(spt.shapiro(data2.SCORE[data2.CLASS=='C']),'\n')
print(spt.shapiro(data2.SCORE[data2.CLASS=='D']),'\n')

print(spt.levene(data2.SCORE[data2.CLASS=='A'],data2.SCORE[data2.CLASS=='B'],
                 data2.SCORE[data2.CLASS=='C'],data2.SCORE[data2.CLASS=='D']),'\n')

print(spt.bartlett(data2.SCORE[data2.CLASS=='A'],data2.SCORE[data2.CLASS=='B'],
                   data2.SCORE[data2.CLASS=='C'],data2.SCORE[data2.CLASS=='D']))

ShapiroResult(statistic=0.9248653054237366, pvalue=0.3288426399230957) 

ShapiroResult(statistic=0.9146616458892822, pvalue=0.24471063911914825) 

ShapiroResult(statistic=0.9890144467353821, pvalue=0.9995220303535461) 

ShapiroResult(statistic=0.9324204325675964, pvalue=0.406475305557251) 

LeveneResult(statistic=1.2523157647372425, pvalue=0.3023830579547205) 

BartlettResult(statistic=2.751186986101656, pvalue=0.4315985695332628)


In [ ]:
print(spt.f_oneway(data2.SCORE[data2.CLASS=='A'],data2.SCORE[data2.CLASS=='B'],
             data2.SCORE[data2.CLASS=='C'],data2.SCORE[data2.CLASS=='D']),'\n') #싸이파이

model3=ols('SCORE ~ C(CLASS)',data=data2).fit()
anova_lm(model3) # 리니어모델을 이용하여 계산

F_onewayResult(statistic=2.471629596005447, pvalue=0.0742083884865057) 



df        sum_sq     mean_sq        F    PR(>F)
C(CLASS)   3.0   3681.562500  1227.18750  2.47163  0.074208
Residual  44.0  21846.416667   496.50947      NaN       NaN

class라는 팩터에 대해 했더니, 

알파가 0.05로 정해져 있을 때, 0.05보다 크니까 유의미한 팩터는 아니라고 할 수 없다. 귀무가설 기각 불가.

그러나 0.05보다 작은 경우, 크게 작은지(0.01) 적게 작은지(통계적 오류가 있다고 할 수 있음). 

R 은 좀 더 세분적으로 보여준다고 한다. 

In [ ]:
model4=ols('SCORE ~ C(GRADE)*C(CLASS)',data=data2).fit()
anova_lm(model4)

df        sum_sq      mean_sq         F    PR(>F)
C(GRADE)            3.0   1241.395833   413.798611  0.863074  0.468369
C(CLASS)            3.0   4983.185764  1661.061921  3.464535  0.025226
C(GRADE):C(CLASS)   9.0   5224.445955   580.493995  1.210757  0.316394
Residual           39.0  18698.444444   479.447293       NaN       NaN

p-val이 유의미한 수치가 나왔기 떄문에, class가 score에 대해, 반이 점수에 대해 유의미할 수 있다고 말할 수 있게된다.

이원 분산분석(교호작용까지 생각하고)을 했는데, 아까 위에서는 귀무가설을 기각할 수 없었다.

이런 경우에는 주어진 데이터가 뭘로 주어졌느냐가 중요하다. class가 같이 들어간 데이터였기 때문에 아래를 선택하는 건 맞지만, 사후검정을 진행해야한다. 유의미 한지 한 번더 검사.

c:c 는 교호작용 테스트.

In [ ]:
from statsmodels.sandbox.stats.multicomp import MultiComparison # 사후검정 진행
from statsmodels.stats.multicomp import pairwise_tukeyhsd

comp = MultiComparison(data2.SCORE, data2.CLASS)


# Bonferroni
opt = comp.allpairtest(spt.ttest_ind, method='bonf')
print(opt[0])

# Tukey's HSD
hsd = pairwise_tukeyhsd(data2['SCORE'], data2['CLASS'], alpha=0.05)
hsd.summary()

Test Multiple Comparison ttest_ind 
FWER=0.05 method=bonf
alphacSidak=0.01, alphacBonf=0.008
group1 group2   stat   pval  pval_corr reject
---------------------------------------------
     A      B -1.1321 0.2698       1.0  False
     A      C -1.2948 0.2088       1.0  False
     A      D -3.0609 0.0057    0.0344   True
     B      C   -0.05 0.9606       1.0  False
     B      D  -1.485 0.1517    0.9104  False
     C      D -1.6151 0.1206    0.7233  False
---------------------------------------------


<class 'statsmodels.iolib.table.SimpleTable'>

여기서는 귀무가설이 기각된다는 것이다. 교호작용까지 고려해서 분석했다는 것이 옳다고 보여준다.

맨 처음 분석은 오류가 있다는 것을 알수있다.

여러 집단이 있을 때, 하나의 요인을 고려하는 것과 (원래 데이터가 그렇다면)다중 요인을 함께 고려했을 때 (교호작용까지) 전자는 문제가 있을 수 있음을 확인할 수 있게 되기도 함. 지금처럼!

곱셉은 교호작용을 고려한 것, 덧셈은 교호작용을 고려하지 않은것.

In [ ]:
data1=pd.read_csv('data_miles.csv',dtype={'fuel':'object'})

model1=ols('miles ~ C(fuel)*C(pad)',data=data1).fit()
anova_lm(model1)

df      sum_sq     mean_sq         F    PR(>F)
C(fuel)          3.0  365.571250  121.857083  3.274005  0.058846
C(pad)           2.0  282.253333  141.126667  3.791732  0.052936
C(fuel):C(pad)   6.0  259.010000   43.168333  1.159828  0.387823
Residual        12.0  446.635000   37.219583       NaN       NaN

0.05보다 크니까 귀무가설 기각이 불가하다. 그러나,

In [ ]:
model11=ols('miles ~ C(fuel)+C(pad)',data=data1).fit()
anova_lm(model11)

df      sum_sq     mean_sq         F    PR(>F)
C(fuel)    3.0  365.571250  121.857083  3.108401  0.052386
C(pad)     2.0  282.253333  141.126667  3.599940  0.048402
Residual  18.0  705.645000   39.202500       NaN       NaN

여기서는 기각할 수 있게 된다. 교호작용이 0.002 정도의 수치에 의해 위에서는 기각할 수 없고 아래서는 기각할 수 있게 된다.

큰 차이이기 때문에 고려를 많이 해봐야 한다. 

일단 이렇게 결과가 나왔다면, 아래 모델을 채택을 하긴 하지만 오류가 있을 수 있기에 사후검정을 진행한다.

In [ ]:
comp2 = MultiComparison(data1['miles'], data1['pad'])


# Bonferroni
opt2 = comp2.allpairtest(spt.ttest_ind, method='bonf')
print(opt2[0])

# Tukey's HSD
hsd2 = pairwise_tukeyhsd(data1['miles'], data1['pad'], alpha=0.05)
hsd2.summary()

Test Multiple Comparison ttest_ind 
FWER=0.05 method=bonf
alphacSidak=0.02, alphacBonf=0.017
group1 group2   stat   pval  pval_corr reject
---------------------------------------------
     X      Y  1.1951 0.2519    0.7557  False
     X      Z -1.1546 0.2676    0.8028  False
     Y      Z -2.3579 0.0335    0.1004  False
---------------------------------------------


<class 'statsmodels.iolib.table.SimpleTable'>

전부 false다. 귀무가설을 기각할 수 없다고 나온 것이다.

전체에서 봤을 때는 pad라는 팩트에 대해서 귀무가설을 기각할 수 있다 하더라도, 사후검정에서는 차이가 있을 것이라는 가설이 기각되니까,

우리가 데이터가 많다면 다르게 랜덤샘플링을 해본다던가 해야한다. 

(보고서에서 기각과 기각하지 않음은 범주형이다. 그것을 결론을 내리는데 있어서 0.05 에서 크냐 작냐는 연속적이다. 0.05보다 많이 큰지 적게 큰지 그런 것을 함께 보는 것도 중요한데... 이럴 때일 수록 주의하면 써야 한다.) 

이지선다에서 결론을 내릴때, 숫자값들이 0.05(알파값)에 가까이 있다면 결론을 조심히 내려야 한다고 하셨다.

교호작용을 포함했을 때와 아닐때와 검정결과가 다르다면 사후분석을 하고, 통게적으로 이런 결론을 내릴것이라고 다 해봐야한다고 했다.

위의 데이터를 꼭 돌려보시길 바란다. 결과가 애매하게 나오기 때문에 더 어렵다. 교호작용 고려 여부나 검정방법에 따라 결과가 다 다르기 때문에.

값이 나오는 것을 보고서에 어떻게 쓸건지 본인이 선택해야 하는 부분이니까. 

결론은 있어도, 가능성은 열어두어 너무 단정적으로 얘기하면 안된다.

# 아래는 진도

r 내용을 사용하는 건 아니지만 r이 있어야돌아가는 듯. 



In [ ]:
import rpy2.robjects as robjs
from rpy2.robjects import r
%load_ext rpy2.ipython
# 변수 이동
%Rpush data1

ValueError: r_home is None. Try python -m rpy2.situation

In [ ]:
import rpy2.robjects as robjs
from rpy2.robjects import r
%load_ext rpy2.ipython
# 변수 이동
%Rpush temp.csv

ValueError: r_home is None. Try python -m rpy2.situation

In [ ]:
print(r('aov_mdl <- aov(data1$miles ~ as.factor(data1$pad),data=data1)'))

In [ ]:
robjs.packages.importr('agricolae')
print(r('duncan.test(aov_mdl, "as.factor(data1$pad)", alpha = 0.05, console = TRUE)'))

위는 r을 깔아야 돌아가는 부분이니.... 안하셔도...

In [ ]:
# 카이제곱 검정 (적합도)

print(spt.chisquare([16, 18, 16, 14, 12, 12]))

print(spt.chisquare([16, 18, 16, 14, 12, 12], f_exp=[16, 16, 16, 16, 16, 8])) 
# 카이스퀘어검정을 할 때, 위에 f_exp 넣지 않으면 자동으로 균일 분포라고 생각한다. 실제로 이렇게 f_exp= 해서 기대도수를 커스텀으로 입력할 수도 있다.
# 전체 도수 개수가 n 이고.... 아까의 예제의 경우 포아송분포-해서 나온 확률과 각 도수를 곱한 것을 저기에 넣으면 된다.
# 만약 f_exp같은데에 아예 함수가 들어간다면 더 편하겠지만 아직까지 그게 다 되는지는 모른다.

print(spt.chisquare([16, 18, 16, 14, 12, 12], ddof=[0,1,2])) # 자유도(범주형인데...) 검사결과로 변수가 이렇게 배열로도 approach할 수 있다.

obs=np.array([31,26,22,18,13,10])
print(spt.chisquare(obs)) # obs가 균일분포를 다르는지 적합도 검정.

Power_divergenceResult(statistic=2.0, pvalue=0.8491450360846096)
Power_divergenceResult(statistic=3.5, pvalue=0.6233876277495822)
Power_divergenceResult(statistic=2.0, pvalue=array([0.84914504, 0.73575888, 0.5724067 ]))
Power_divergenceResult(statistic=15.7, pvalue=0.007754884452437287)


똑같은 카이스퀘어검정을 했는데 값이 다르게 나온다.

결국 귀무가설의 분포를 따른다는 결론을 낼 수 있다.


In [ ]:
# 카이제곱 검정 (교차분석)
homd=pd.read_csv('hom_ind.csv',dtype={'QUALITY' : 'object'})
homd.head()

COUNTS LINE QUALITY
0      20    A       1
1      16    A       2
2      24    A       3
3      28    A       4
4      12    A       5

counts - 퀄리티에 대한 분포가 라인에 대해서 분포가 동일한가?를 보고싶은 것이 아래의 코드이다. 

chi2_contingency테이블에 따라서 다른...

In [ ]:
print(spt.chi2_contingency([homd.COUNTS[homd.QUALITY=='1'],homd.COUNTS[homd.QUALITY=='2'],
                           homd.COUNTS[homd.QUALITY=='3'],homd.COUNTS[homd.QUALITY=='4'],homd.COUNTS[homd.QUALITY=='5']]))

(38.91388658559004, 0.00010872733726640437, 12, array([[15.5 , 15.5 , 15.5 , 15.5 ],
       [21.  , 21.  , 21.  , 21.  ],
       [20.5 , 20.5 , 20.5 , 20.5 ],
       [21.75, 21.75, 21.75, 21.75],
       [21.25, 21.25, 21.25, 21.25]]))


두 개가 동질하지 않다는 말이지만 이걸 막무가내로 이야기 하지 않아요.

라인을 고정시켰을 때, 라인별 간의 퀄리티 차이는 동질하지 않다고 말을 합니다. (라인간의 품질차이가 존재하지 않았다.)

말을 잘해야해용~_~ 검정에 차이는 크지 않음.

하나를 고정하고 다른 독립변수를 차이를 주며 본다는 것은 바로 이 경우.



In [ ]:
ss=np.array([[homd.COUNTS[0:5]],[homd.COUNTS[5:10]],[homd.COUNTS[10:15]],[homd.COUNTS[15:20]]])
print(ss)

[[[20 16 24 28 12]]

 [[13 17 30 15 25]]

 [[20 20 15 15 30]]

 [[ 9 31 13 29 18]]]


(아래)직접 만들어서 한다면 이렇게 쓰면됩니다. (하드코딩)

E값: 분포가 어떤 분포라고 정해주어서 이 값을 자동으로 넣는 라이브러리는 아직까지 없다.

그렇다면 sci-py로 직접 계산 다 해서 해봐야 합니다.

적합도 검정과 다르다는 것을 보여주기 위해 아래를 쓴 것.

검정 방법이 같기 때문에 어떤게 적합도 검정을 해야할지, 교차분석을 해야할지, 연구자가 선택하는 것.

In [ ]:
t_chi2=0
for i in range(4):
    for j in range(5):
        O = ss[i][0][j]
        E = (ss[i][0][0]+ss[i][0][1]+ss[i][0][2]+ss[i][0][3]+ss[i][0][4])*(ss[0][0][j]+ss[1][0][j]+ss[2][0][j]+ss[3][0][j]) / 400
        t_chi2 += (O-E)**2/E
print(t_chi2)

In [ ]:
p_val = 1 - spt.chi2.cdf(t_chi2, 12)
print(p_val)